---
title: Maker Park - Proposed park and maker space in Brooklyn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: pretty
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
permalink: pretty
baseurl: "/"
url: http://localhost:4000
exclude:
- Gemfile
- Gemfile.lock
- sass
- bower_components
- bower.json
- node_modules
- Gruntfile.js
- package.json
- README.md
- ref.txt
- tooling.md
- src
- ".nojekyll"
